library(tidyverse)
setwd("/Users/Bhandal/Desktop")
popsize <- read_tsv("/Users/Bhandal/Downloads/pop_size.csv")
library(ggplot2)
library(dplyr)
library(tibble)
library(readr)
popsize
head(popsize, 10)
tail(popsize, 10)
glimpse(popsize)
view(popsize)
ndvi <- read_tsv("/Users/Bhandal/Downloads/ndvi.csv")
head(ndvi)
newdata <- select(ndvi, Herd, NDVI_May)
head(newdata)
select(ndvi, -Herd)
select(ndvi, Herd:NDVI_May)
tail(ndvi, 20)
filter(ndvi, Herd=="WAH")
popsize
filter(popsize, Year>1975, Year<=1980)
filter(popsize, Year %in% c(1980, 1982, 1984, 1986))
arrange(distinct(select(popsize, Herd)), Herd)
popsize %>% select(Herd) %>% distinct() %>% arrange(Herd)
popsize %>% select(Year) %>% distinct() %>% arrange(Year)
